import yaml
import datetime


def header() -> str:
    """
    Return a header string.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    title = "SPEBT detector system configuration YAML file."
    header = ""
    title_bar = "=" * len(title)
    header += f"# {title_bar}\n# {title}\n# {title_bar}\n"
    header += "# Description: This file is generated by PyDetgen package.\n"
    header += "# Visit https://spebt.github.io/pydetgen for more information.\n"
    header += f"# Date: {timestamp}\n\n"
    return header


def write(config_dict: dict, fname: str) -> None:
    """
    Write configuration dictionary to a yaml file.
    """
    with open(fname, "w") as outfile:
        outfile.write(header())
        yaml.dump(
            config_dict,
            outfile,
            default_flow_style=None,
            sort_keys=False,
        )
